
package com.zimbra.wsdl.zimbraservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "zcsAdminService", targetNamespace = "http://www.zimbra.com/wsdl/ZimbraService.wsdl", wsdlLocation = "https://laumail.laumayer.com/service/wsdl/ZimbraService.wsdl")
public class ZcsAdminService
    extends Service
{

    private final static URL ZCSADMINSERVICE_WSDL_LOCATION;
    private final static WebServiceException ZCSADMINSERVICE_EXCEPTION;
    private final static QName ZCSADMINSERVICE_QNAME = new QName("http://www.zimbra.com/wsdl/ZimbraService.wsdl", "zcsAdminService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://laumail.laumayer.com/service/wsdl/ZimbraService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ZCSADMINSERVICE_WSDL_LOCATION = url;
        ZCSADMINSERVICE_EXCEPTION = e;
    }

    public ZcsAdminService() {
        super(__getWsdlLocation(), ZCSADMINSERVICE_QNAME);
    }

    public ZcsAdminService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ZCSADMINSERVICE_QNAME, features);
    }

    public ZcsAdminService(URL wsdlLocation) {
        super(wsdlLocation, ZCSADMINSERVICE_QNAME);
    }

    public ZcsAdminService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ZCSADMINSERVICE_QNAME, features);
    }

    public ZcsAdminService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZcsAdminService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ZcsAdminPortType
     */
    @WebEndpoint(name = "zcsAdminServicePort")
    public ZcsAdminPortType getZcsAdminServicePort() {
        return super.getPort(new QName("http://www.zimbra.com/wsdl/ZimbraService.wsdl", "zcsAdminServicePort"), ZcsAdminPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZcsAdminPortType
     */
    @WebEndpoint(name = "zcsAdminServicePort")
    public ZcsAdminPortType getZcsAdminServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.zimbra.com/wsdl/ZimbraService.wsdl", "zcsAdminServicePort"), ZcsAdminPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ZCSADMINSERVICE_EXCEPTION!= null) {
            throw ZCSADMINSERVICE_EXCEPTION;
        }
        return ZCSADMINSERVICE_WSDL_LOCATION;
    }

}
